management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
      base-path: "/manage"

  server:
    port: 9292

info:
  app:
    name: hello-actuator
    company: sh
logging:
    level:
      hello.controller: debug
