management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

info:
  app:
    name: hello-actuator
    company: sh
